export const categories = [
    {
      id: 1,
      name: 'Rings',
      img: "img/ring.jpg",
      price: 50
    },
    {
      id: 2,
      name: 'Bracelets',
      img: "img/bracelet.jpg",
      price: 50
    },
    {
      id: 3,
      name: 'Earrings',
      img: "img/earrings.jpg",
      price: 50
    },
    {
      id: 4,
      name: 'Necklaces',
      img: "img/necklace.jpg",
      price: 50
    },
]

export const productDetails = {
    id: 5, 
    name: 'ring1',
    img: 'img/ring5.jpg',
    price: 50,
    available: true,
    description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
    size: 'small',
    inCart: false,
    count: 0,
    total: 0
}

export const products = [
    // RINGS
    {
        id: 5, 
        category: 'rings',
        name: 'ring1',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6, 
        category: 'rings',
        name: 'ring2',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 7, 
        category: 'rings',
        name: 'ring3',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 8, 
        category: 'rings',
        name: 'ring4',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 9, 
        category: 'rings',
        name: 'ring5',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 10, 
        category: 'rings',
        name: 'ring6',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 11, 
        category: 'rings',
        name: 'ring7',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 12, 
        category: 'rings',
        name: 'ring8',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 13, 
        category: 'rings',
        name: 'ring9',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 14, 
        category: 'rings',
        name: 'ring10',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 15, 
        category: 'rings',
        name: 'ring11',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 16, 
        category: 'rings',
        name: 'ring12',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    // NECKLACES
    {
        id: 17,
        category: 'necklace',
        name: 'necklace1',
        img: 'img/necklace1.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 18,
        category: 'necklace',
        name: 'necklace2',
        img: 'img/necklace1.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 19,
        category: 'necklace',
        name: 'necklace3',
        img: 'img/necklace1.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 20,
        category: 'necklace',
        name: 'necklace4',
        img: 'img/necklace1.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 21,
        category: 'necklace',
        name: 'necklace5',
        img: 'img/necklace1.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 22,
        category: 'necklace',
        name: 'necklace6',
        img: 'img/necklace1.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 23,
        category: 'necklace',
        name: 'necklace7',
        img: 'img/necklace1.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    // EARRINGS
    {
        id: 24,
        category: 'earring',
        name: 'earring1',
        img: '/img/earring1.jpg',
        price: 20,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 25,
        category: 'earring',
        name: 'earring2',
        img: '/img/earring1.jpg',
        price: 20,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 26,
        category: 'earring',
        name: 'earring3',
        img: '/img/earring1.jpg',
        price: 20,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 27,
        category: 'earring',
        name: 'earring4',
        img: '/img/earring1.jpg',
        price: 20,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 28,
        category: 'earring',
        name: 'earring5',
        img: '/img/earring1.jpg',
        price: 20,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    // BRACELETS
    {
        id: 29,
        category: 'bracelet',
        name: 'bracelet1',
        img: '/img/bracelet1.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 30,
        category: 'bracelet',
        name: 'bracelet2',
        img: '/img/bracelet1.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 31,
        category: 'bracelet',
        name: 'bracelet3',
        img: '/img/bracelet1.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 32,
        category: 'bracelet',
        name: 'bracelet4',
        img: '/img/bracelet1.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 33,
        category: 'bracelet',
        name: 'bracelet5',
        img: '/img/bracelet1.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
]