export const categories = [
    {
      id: 1,
      name: 'Rings',
      img: "img/ring.jpg",
      price: 50
    },
    {
      id: 2,
      name: 'Bracelets',
      img: "img/bracelet.jpg",
      price: 50
    },
    {
      id: 3,
      name: 'Earrings',
      img: "img/earrings.jpg",
      price: 50
    },
    {
      id: 4,
      name: 'Necklaces',
      img: "img/necklace.jpg",
      price: 50
    },
]

export const productDetails = {
    id: 5, 
    name: 'ring1',
    img: 'img/ring5.jpg',
    price: 50,
    available: true,
    description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
    size: 'small',
    inCart: false,
    count: 0,
    total: 0
}

export const products = [
    // RINGS
    {
        id: 5, 
        category: 'rings',
        name: 'Leaf Ring Set',
        img: 'img/ring1.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6, 
        category: 'rings',
        name: 'Blue Ring',
        img: 'img/ring2.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 7, 
        category: 'rings',
        name: '3-tiered Ring',
        img: 'img/ring3.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 8, 
        category: 'rings',
        name: 'Cluster Ring',
        img: 'img/ring4.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 9, 
        category: 'rings',
        name: 'Crown Ring',
        img: 'img/ring5.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 10, 
        category: 'rings',
        name: 'Diamond Set Ring',
        img: 'img/ring6.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 11, 
        category: 'rings',
        name: 'Red Square Ring',
        img: 'img/ring7.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 12, 
        category: 'rings',
        name: 'Diamond Circle Ring',
        img: 'img/ring8.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 13, 
        category: 'rings',
        name: 'Emerald and Diamond Set',
        img: 'img/ring9.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 14, 
        category: 'rings',
        name: 'Diamond Studded Ring',
        img: 'img/ring10.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 15, 
        category: 'rings',
        name: 'Ruby Ring',
        img: 'img/ring11.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 16, 
        category: 'rings',
        name: 'Fancy Shape Ring',
        img: 'img/ring12.jpg',
        price: 50,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    // NECKLACES
    {
        id: 17,
        category: 'necklace',
        name: 'Heart Necklace',
        img: 'img/necklace1.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 18,
        category: 'necklace',
        name: 'Olympic Range Pendant',
        img: 'img/necklace2.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 19,
        category: 'necklace',
        name: 'Mother Child Pendant',
        img: 'img/necklace3.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 20,
        category: 'necklace',
        name: 'Pearl Necklace',
        img: 'img/necklace4.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 21,
        category: 'necklace',
        name: 'Music Necklace',
        img: 'img/necklace5.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 22,
        category: 'necklace',
        name: 'Yellow Leaf Necklace',
        img: 'img/necklace6.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 23,
        category: 'necklace',
        name: 'Purple Stone Necklace',
        img: 'img/necklace7.jpg',
        price: 30,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    // EARRINGS
    {
        id: 24,
        category: 'earring',
        name: 'Blue and Diamond Earrings',
        img: '/img/earring1.jpg',
        price: 20,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 25,
        category: 'earring',
        name: 'Diamond Earrings',
        img: '/img/earring2.jpg',
        price: 20,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 26,
        category: 'earring',
        name: 'Cyan and Green Set',
        img: '/img/earring3.jpg',
        price: 20,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 27,
        category: 'earring',
        name: 'Cyan and Green Set',
        img: '/img/earring3.jpg',
        price: 20,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 28,
        category: 'earring',
        name: 'Cyan and Green Set',
        img: '/img/earring3.jpg',
        price: 20,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    // BRACELETS
    {
        id: 29,
        category: 'bracelet',
        name: 'bracelet1',
        img: '/img/bracelet1.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 30,
        category: 'bracelet',
        name: 'Gold Bracelet',
        img: '/img/bracelet1.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 31,
        category: 'bracelet',
        name: 'Gold Bracelet',
        img: '/img/bracelet1.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 32,
        category: 'bracelet',
        name: 'Gold Bracelet',
        img: '/img/bracelet1.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 33,
        category: 'bracelet',
        name: 'Gold Bracelet',
        img: '/img/bracelet1.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'small',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 34,
        category: 'other',
        name: 'Engraved Watch',
        img: '/img/watchEngrave.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'N/A',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 35,
        category: 'other',
        name: 'Engraved Steel Plate',
        img: '/img/steelPlateEngrave.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'N/A',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 36,
        category: 'other',
        name: 'Skeletal Studies Sketch',
        img: '/img/skelOne.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'N/A',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 37,
        category: 'other',
        name: 'Skeletal Studies Sketch',
        img: '/img/skelTwo.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'N/A',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 38,
        category: 'other',
        name: 'Skeletal Studies Sketch',
        img: '/img/skelThree.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'N/A',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 39,
        category: 'other',
        name: 'Skeletal Studies Sketch',
        img: '/img/skelFour.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'N/A',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 40,
        category: 'other',
        name: 'Skeletal Studies Sketch',
        img: '/img/skelFive.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'N/A',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 41,
        category: 'other',
        name: 'Skeletal Studies Sketch',
        img: '/img/skelSix.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'N/A',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 42,
        category: 'other',
        name: 'Skeletal Studies Sketch',
        img: '/img/skelSeven.jpg',
        price: 35,
        available: true,
        description: 'Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics',
        size: 'N/A',
        inCart: false,
        count: 0,
        total: 0
    },
]
